server:
  port: 5566

#spring:
 # profiles:
  #   include: redis

swagger:
  enabled: true
spring:
  data:
    mongodb:
      uri: mongodb://ads:75PN76Db66En@139.219.133.255:27017/ads
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: root
      password: 123
  batch:
      table-prefix: batch
      initializer:
        enabled: true  #这里是允许自动初始化spring batch的数据库
      job:
        enabled: false
scheduled:
      corn:
          test: 1/1 * * * * ?
